server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transporte_publico
    username: postgres
    password: 250308
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
